### PR TITLE
use the new locking API

### PR DESCRIPTION
**Pull request by aspiers**
https://github.com/crowbar/barclamp-crowbar/pull/1353 introduced a new OO-style locking API.

Cloud 5 backport of part of https://github.com/crowbar/crowbar-openstack/pull/37

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by jsuchome** [comment]
+1 codewise, as backport (not tested)

**Comment by aspiers** [comment]
Gate succeeded via https://ci.suse.de/job/openstack-mkcloud/8056/ (see https://github.com/crowbar/barclamp-crowbar/pull/1353)

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
