### PR TITLE
Allow deploying swift on SLE12 nodes

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
:+1: so far

**Comment by jsuchome** [comment]
Looks good (but I'd like to test it)

**Comment by vuntz** [comment]
> Looks good (but I'd like to test it)

Make sure to use my other barclamp-swift PR if you test it, as they unbreak various things.

**Comment by vuntz** [comment]
Forgot to mention that tempest passed.

**Comment by jsuchome** [comment]
Tested deployment, and some simple swift commands, seems to work. (currently at c13 if anyone wants to look)

+1

**Comment by bmwiedemann** [comment]
:+1:

**Pull request merged**
